### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by lakshmirajani** [lakshmaji/Thumbnail#22] opened 2019-02-21 10:31 UTC
Unable to load FFProbe

**Comment by lakshmaji** [comment] 2019-02-22 17:12
Similar issue [18](https://github.com/lakshmaji/Thumbnail/issues/18)

**Comment by lakshmaji** [comment] 2019-02-27 15:37
Closing this as a duplicate of [18](https://github.com/lakshmaji/Thumbnail/issues/18) #18

**Closed as completed by lakshmaji** 2019-02-27 15:37 UTC
